coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "src/*/test/**"
  - "src/_deprecated/**"
  - "build/**"
  - "devel/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
