roi:
  mode: track
road_type: 3
filters:
  obstacle_height:
    enable: true
    max_z_span: 0.25
    min_distance: 8.0
    min_points_to_judge: 8
tracker:
  enable: true
topology:
  enable: true
mode_presets:
  track:
    adaptive_y:
      ramp_start_x: 8.0
      far_y_half: 3.0
      near_y_half: 10.0
    cluster:
      cluster_tolerance:
      - 0.15
      - 0.25
      - 0.28
      - 0.35
      - 0.38
      - 0.4
      - 0.42
    center_exclusion:
      enable: true
      y_half: 1.5
      start_distance: 15.0
stacked_cone_detection:
  vertical_layers:
    layer_height: 0.2
    max_layers: 4
fusion:
  projection:
    max_pixel_distance: 60.0
